language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      -libhunspell-dev

r_github_packages:
    - hadley/testthat
    - jimhester/covr

env:
 global:
   - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::coveralls()'