language: r

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel
    - os: osx
      disable_homebrew: true

sudo: false
cache: packages
cran: http://cran.rstudio.com
warnings_are_errors: true

r_github_packages:
    - hadley/testthat
    - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::coveralls()'