language: r
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx

sudo: false
cache: packages
cran: http://cran.rstudio.com
disable_homebrew: true
warnings_are_errors: true

r_github_packages:
    - hadley/testthat
    - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::coveralls()'