os:
  - linux
  - osx

language: r

r:
  - oldrel
  - release
  - devel

env:
  global:
    - CRAN: http://cran.rstudio.com

sudo: false
cache: packages
warnings_are_errors: true

brew_packages: hunspell

addons:
  apt:
    packages:
      -libhunspell-dev

r_github_packages:
    - hadley/testthat
    - jimhester/covr

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - test $TRAVIS_R_VERSION_STRING = "release" && Rscript -e 'covr::coveralls()'